#!/usr/bin/env bash
# FR-SRC-011 — generate Docker bind mounts and host-path manifest from sources config.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
CONFIG_PATH="${ROOT_DIR}/config/sources.yaml"
MANIFEST_PATH="${ROOT_DIR}/config/host-path-manifest.json"
OVERRIDE_PATH="${ROOT_DIR}/infra/docker/docker-compose.override.generated.yml"
ENV_FILE="${ROOT_DIR}/.env"

collect_paths() {
  python3 - <<'PY' "$CONFIG_PATH" "$ENV_FILE"
import json
import os
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    yaml = None

paths: list[str] = []

env_file = Path(sys.argv[2])
if env_file.is_file():
    for line in env_file.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line.startswith("PKB_SOURCE_DIRS="):
            raw = line.split("=", 1)[1].strip().strip('"').strip("'")
            paths.extend([item.strip() for item in raw.split(",") if item.strip()])

config_path = Path(sys.argv[1])
if yaml and config_path.is_file():
    data = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
    for source in data.get("sources", []):
        if source.get("type") == "local_folder":
            for item in source.get("paths", []):
                if item:
                    paths.append(str(item))

seen: list[str] = []
for item in paths:
    expanded = str(Path(item).expanduser())
    if expanded not in seen:
        seen.append(expanded)

print(json.dumps(seen))
PY
}

PATHS_JSON="$(collect_paths)"
PATH_COUNT="$(python3 - <<'PY' "$PATHS_JSON"
import json, sys
print(len(json.loads(sys.argv[1])))
PY
)"

mkdir -p "$(dirname "$MANIFEST_PATH")"
mkdir -p "$(dirname "$OVERRIDE_PATH")"

python3 - <<'PY' "$PATHS_JSON" "$MANIFEST_PATH" "$OVERRIDE_PATH"
import json
import sys
from pathlib import Path

paths = json.loads(sys.argv[1])
manifest_path = Path(sys.argv[2])
override_path = Path(sys.argv[3])

mappings: dict[str, str] = {}
services: list[str] = []

for index, host_path in enumerate(paths):
    slug = f"host-{index}"
    container_path = f"/sources/{slug}"
    mappings[host_path] = container_path
    mappings[str(Path(host_path).expanduser())] = container_path
    services.append(f"      - {host_path}:{container_path}:ro")

manifest_path.write_text(json.dumps({"mappings": mappings}, indent=2) + "\n", encoding="utf-8")

volume_lines = "\n".join(services) if services else "      - ../../config/host-path-manifest.json:/app/config/host-path-manifest.json:ro"
if not services:
    volume_lines += "\n      - ../../config:/app/config:ro"

host_mount = "      - ${HOME}:/host:ro"
volume_lines = f"{host_mount}\n{volume_lines}"

override = f"""# Generated by infra/scripts/prepare-host-sources.sh — do not edit manually.
services:
  api:
    volumes:
{volume_lines}
  worker:
    volumes:
{volume_lines}
"""
override_path.write_text(override, encoding="utf-8")
print(f"Prepared {len(paths)} host source mount(s)")
PY
